---
title: "Assignment_1"
author: "Ted Ladas"
date: "1/30/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(stats)
require(roperators)
```

# Question 1

## a)

Test for independence in a 2-way contingency table with Yate's Continuity correction. 

## b) 

## c)

## d)

```{r}

rm(list = ls())

report_results <- function(diff_check=diff, p_value=p_auto, p_value_manual=p_manual, sig_lvl=alpha){
  
  if(diff_check == 0){
  cat('\nReject the null hypothesis under the 5% significance level'%s*%(p_value<sig_lvl))
  cat('\nNo evidence to reject the null hypothesis under the 5% significance level'%s*%(p_value>sig_lvl))
  cat('\n     with p-value:', p_value)
} else{warning('\nWARNING: manual and automatic p-value are not the same')
  cat('\ndiff between p-value calculations:', diff_check)
  cat('\np-value manual calc:', p_value_manual)
  cat('\np-value auto   calc:', p_value)
  }
  
}
# setting up the table and helper variables.
O <- as.table(rbind(c(688, 650),c(21, 59)))
dimnames(O) <- list(smokers = c("Smokers", "Nonsmokers"), lung_cancer=c("Cancer", "Control"))

# Manual Calculation of p-value
alpha <- 0.05
n<-sum(O)
row_n <- rowSums(O)
col_n <- colSums(O)
E <- outer(row_n,col_n)/n # expected cell counts
X2 <- sum((abs(O-E)-0.5)^2/E) # Yate's continuity correction
df <- (nrow(O)-1)*(ncol(O)-1) # df=1 because we have 2x2 matrix

p_manual <- 1 - pchisq(X2,df = df)


# using the chisq.test method
p_auto <- chisq.test(O)$p.value
diff = round(p_manual - p_auto, 8)

report_results(diff_check=diff, p_value=p_auto, p_value_manual=p_manual, sig_lvl=alpha)

```

## e)


